model_path: unlearning_ckpt2/ft_model_10_epochs_inst_lr1e-3
model_family: llama2-7b

# save_dir: ${model_path}/eval_results/ds_size${ds_size}

#dataset path for each of the 4 datasets to be evaluated
# data_path: [locuslab/TOFU]
data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
split: forget01_perturbed
split_list:
  - retain_perturbed
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}

save_dir: forget_only_system_prompt_${model_family}_${split}

# question_key: [question]
# answer_key: [answer]
# base_answer_key: [answer]
# perturbed_answer_key: [perturbed_answer]
# eval_task: [eval_real_world_wo_options]


# question_key: [question]
# answer_key: [answer]
# base_answer_key: [paraphrased_answer]
# perturbed_answer_key: [perturbed_answer]
# eval_task: [eval_log_forget]


question_key: [question, question, question, question]
answer_key: [answer, answer, answer, answer]

base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]

generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 300

overwrite: true
use_pretrained: true

batch_size: 10
reinitialize_weights: false
retain_result: null






